package gradowska.katarzyna.filmsapp.presentation.singleMovie

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.bundle.bundleOf
import androidx.fragment.app.Fragment
import androidx.fragment.app.setFragmentResult
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.navigation.fragment.navArgs
import gradowska.katarzyna.filmsapp.databinding.FragmentSingleMovieBinding
import gradowska.katarzyna.filmsapp.presentation.recyclerList.compose.SingleMovie
import kotlinx.coroutines.launch
import org.koin.androidx.viewmodel.ext.android.viewModel
import org.koin.core.parameter.parametersOf

class SingleMovieFragment : Fragment() {

    private var _binding: FragmentSingleMovieBinding? = null
    private val binding get() = _binding!!

    private val args: SingleMovieFragmentArgs by navArgs()

    private val viewModel: SingleMovieViewModel by viewModel { parametersOf(args.idMovie) }

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentSingleMovieBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        observe()
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    private fun observe() {
        lifecycleScope.launch {
            lifecycle.repeatOnLifecycle(Lifecycle.State.STARTED) {
                viewModel.movieDetails.collect { movieDetailsDataModel ->
                    if (movieDetailsDataModel == null) return@collect
                    binding.singleMovieCompose.setContent {
                        SingleMovie(
                            titleText = movieDetailsDataModel.movieTitle,
                            movieImage = movieDetailsDataModel.moviePhoto,
                            description = movieDetailsDataModel.movieDescription,
                            rate = movieDetailsDataModel.movieRate,
                            isLiked = movieDetailsDataModel.movieLiked,
                            viewsCounter = movieDetailsDataModel.movieVoteCount,
                            quote = movieDetailsDataModel.movieTagline,
                            productionCountries = movieDetailsDataModel.movieProductionCountries,
                            originalLanguage = movieDetailsDataModel.movieOriginalLanguage,
                            originalTitle = movieDetailsDataModel.movieOriginalTitle,
                            onFavouriteClick = {
                                viewModel.favouriteIconClicked(
                                    movieDetailsDataModel
                                )
                            },
                            movieBackdropPath = movieDetailsDataModel.movieBackdropPath,
                            budget = movieDetailsDataModel.movieBudget,
                            revenue = movieDetailsDataModel.movieRevenue,
                            genres = movieDetailsDataModel.movieGenres,
                            runtime = movieDetailsDataModel.movieRuntime,
                            dateOfProduction = movieDetailsDataModel.movieReleaseDate
                        )

                    }
                    with(binding) {
                        //TODO event should be generated by view model
                        setFragmentResult(
                            MOVIE_FRAGMENT_RESULT,
                            bundleOf(
                                MOVIE_FRAGMENT_FAVOURITE_KEY to movieDetailsDataModel.movieLiked,
                                MOVIE_FRAGMENT_ID_KEY to movieDetailsDataModel.movieID,
                            )
                        )
                    }
                }
            }
        }
    }

    companion object {
        const val MOVIE_FRAGMENT_RESULT = "MOVIE_FRAGMENT_RESULT"
        const val MOVIE_FRAGMENT_FAVOURITE_KEY = "MOVIE_FRAGMENT_FAVOURITE_KEY"
        const val MOVIE_FRAGMENT_ID_KEY = "MOVIE_FRAGMENT_ID_KEY"
    }
}
